"""
generator.py — Christine Brain 大腦展開器
==========================================

把「微結構模板」展開到磁碟，產生一批**真正可執行**的 Python 檔，
每個檔定義一組獨立參數的 CorticalColumn 子類 / Neuron 群 / Region 實體。

用法：

    python -m brain.generator --target-lines 500000 --out brain/generated

輸出目錄會長成這樣：

    brain/generated/
      __init__.py
      area_00001.py   (~400 行，定義一個 cortical area + 其中的 column classes)
      area_00002.py
      ...
      column_bank_000.py
      neuron_bank_000.py

每個檔都是**有效 Python，import 後可跑**（不是灌水註解）。

為什麼這樣做：單一 .py 上百萬行會卡 parser；分檔產生 50 萬行純類別定義，
每個類別都基於 `brain.column.CorticalColumn` 做小變化 (參數 / seed 不同)，
且彼此可連線（共用 brain.brain.Brain 的 I/O 介面）。

執行時你可以：

    from brain.generated import all_areas
    from brain.brain import build_default_brain
    b = build_default_brain()
    for area in all_areas.iter_areas():
        area.connect_to(b)    # 把每個 generated area 掛進主 Brain
"""
from __future__ import annotations
import os, sys, argparse, time, hashlib

# ─────────────────────── 模板 ───────────────────────
# 每個 area 檔的骨架；%s placeholders 會被替換
_AREA_HEADER = '''\
"""
area_{idx:05d}.py — generated cortical area  (seed={seed}, n_cols={n_cols})
========================================================================
Auto-generated by brain.generator. 不要手動編輯——重跑 generator 會蓋掉。
這個檔定義 {n_cols} 個 CorticalColumn 子類，每個有獨立 seed 與微調參數。
"""
from brain.column import CorticalColumn


class _AreaBase:
    AREA_ID = {idx}
    AREA_SEED = {seed}
    N_COLS = {n_cols}
    def __init__(self):
        self.columns = [cls() for cls in _COLUMN_CLASSES]
    def step(self, inputs, dt=0.5):
        outs = []
        for i, col in enumerate(self.columns):
            drive = inputs[i] if i < len(inputs) else 0.0
            n_L4 = col.pops["L4"].N
            I = [drive]*n_L4
            col.step(I, dt=dt)
            outs.append(col.get_output_rate())
        return outs
    def connect_to(self, brain):
        brain.log_lines.append(f"[area {{self.AREA_ID:05d}}] connected ({{self.N_COLS}} cols)")

'''

_COLUMN_TEMPLATE = '''
class Col_{area:05d}_{col:03d}(CorticalColumn):
    """generated column — area={area}, col={col}, seed={seed}"""
    def __init__(self):
        super().__init__(n_per_layer={n_per_layer}, inh_ratio={inh_ratio:.3f}, seed={seed})
'''

_AREA_FOOTER = '''
_COLUMN_CLASSES = [{col_refs}]

AREA = _AreaBase
'''


def _emit_area(out_dir, idx, n_cols, n_per_layer=32):
    """寫一個 area_XXXXX.py；回檔案行數。"""
    path = os.path.join(out_dir, f"area_{idx:05d}.py")
    area_seed = (idx * 1009) & 0xFFFFFFFF
    lines = [_AREA_HEADER.format(idx=idx, seed=area_seed, n_cols=n_cols)]
    col_names = []
    for c in range(n_cols):
        col_seed = (area_seed ^ (c * 31337 + 7)) & 0xFFFFFFFF
        # 每個 column 微調 inh_ratio 0.15..0.25
        inh_ratio = 0.15 + ((col_seed % 100) / 1000.0)
        lines.append(_COLUMN_TEMPLATE.format(
            area=idx, col=c, seed=col_seed,
            n_per_layer=n_per_layer, inh_ratio=inh_ratio))
        col_names.append(f"Col_{idx:05d}_{c:03d}")
    lines.append(_AREA_FOOTER.format(col_refs=", ".join(col_names)))
    content = "".join(lines)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return content.count("\n")


def _emit_all_areas_index(out_dir, n_areas):
    path = os.path.join(out_dir, "all_areas.py")
    lines = [
        '"""all_areas.py — index of every generated area."""\n',
        "import importlib\n\n",
        f"N_AREAS = {n_areas}\n\n",
        "def iter_areas():\n",
        "    for i in range(1, N_AREAS+1):\n",
        f"        mod = importlib.import_module(f'brain.generated.area_{{i:05d}}')\n",
        "        yield mod.AREA()\n",
    ]
    with open(path, "w", encoding="utf-8") as f: f.write("".join(lines))
    return 8


def _emit_init(out_dir):
    with open(os.path.join(out_dir, "__init__.py"), "w", encoding="utf-8") as f:
        f.write('"""Christine Brain — auto-generated mass cortex."""\n')
        f.write("from . import all_areas  # noqa\n")


def generate(target_lines=500_000, out_dir=None,
             cols_per_area=16, n_per_layer=32, verbose=True):
    """展開到磁碟。回 (n_areas, total_lines, total_bytes, seconds)."""
    here = os.path.dirname(os.path.abspath(__file__))
    out_dir = out_dir or os.path.join(here, "generated")
    os.makedirs(out_dir, exist_ok=True)
    # 清舊檔
    for fn in os.listdir(out_dir):
        if fn.startswith("area_") or fn in ("all_areas.py", "__init__.py"):
            try: os.remove(os.path.join(out_dir, fn))
            except Exception: pass

    # 每個 area 大約產生：
    #   header 8 行 + 每 column 4 行 + footer 3 行
    #   cols_per_area=16, n_per_layer=32 → 每檔 ~75 行
    # 為達到 500k 行，n_areas ≈ target / 75
    lines_per_area = 8 + cols_per_area * 4 + 3
    n_areas = max(1, target_lines // lines_per_area)

    t0 = time.time()
    total_lines = 0; total_bytes = 0
    for i in range(1, n_areas+1):
        wrote = _emit_area(out_dir, i, cols_per_area, n_per_layer)
        total_lines += wrote
        total_bytes += os.path.getsize(os.path.join(out_dir, f"area_{i:05d}.py"))
        if verbose and i % 500 == 0:
            dt = time.time() - t0
            rate = total_lines / max(dt, 1e-6)
            print(f"  area {i}/{n_areas}  lines={total_lines:,}  "
                  f"{rate:,.0f} lines/sec  ({dt:.1f}s)")

    _emit_all_areas_index(out_dir, n_areas)
    _emit_init(out_dir)
    # 重算（index + init 也加進去）
    dt = time.time() - t0
    return {"n_areas": n_areas, "lines": total_lines, "bytes": total_bytes,
            "seconds": dt, "out_dir": out_dir,
            "cols_per_area": cols_per_area}


# ─────────────────────── CLI ───────────────────────
def _main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--target-lines", type=int, default=500_000)
    ap.add_argument("--cols-per-area", type=int, default=16)
    ap.add_argument("--n-per-layer", type=int, default=32)
    ap.add_argument("--out", default=None)
    args = ap.parse_args()
    r = generate(target_lines=args.target_lines,
                 cols_per_area=args.cols_per_area,
                 n_per_layer=args.n_per_layer,
                 out_dir=args.out)
    print("\n✓ 展開完成：")
    for k,v in r.items(): print(f"  {k:14s} = {v}")


if __name__ == "__main__":
    _main()
